development:
  adapter: postgresql
  encoding: unicode
  database: DailyQuestions_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: DailyQuestions_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: DailyQuestions_production
  pool: 5
  username:
  password:
